
INSERT INTO PRODUCT (NAME) VALUES ('SHOES');
INSERT INTO PRODUCT (NAME) VALUES ('CAP');
INSERT INTO BRAND (NAME) VALUES ('PUMA');
INSERT INTO BRAND (NAME) VALUES ('ADIDAS');
INSERT INTO PRODUCT_BRAND_MAPPING (BRAND_ID, PRODUCT_ID) VALUES (1, 1);
INSERT INTO PRODUCT_BRAND_MAPPING (BRAND_ID, PRODUCT_ID) VALUES (2, 1);
INSERT INTO PRODUCT_BRAND_MAPPING (BRAND_ID, PRODUCT_ID) VALUES (2, 2);

INSERT INTO PRODUCT_DETAILS (ID, PROD_BRAND_MAP_ID , COLOR , PRICE , SIZE , SELLER ) VALUES (1,1, 'YELLOW', 100, 5, 'GADA ELECTRONICS');
INSERT INTO PRODUCT_DETAILS (ID, PROD_BRAND_MAP_ID , COLOR , PRICE , SIZE , SELLER ) VALUES (2,1, 'YELLOW', 101, 6, 'GADA ELECTRONICS');
INSERT INTO PRODUCT_DETAILS (ID, PROD_BRAND_MAP_ID , COLOR , PRICE , SIZE , SELLER ) VALUES (3,1, 'RED', 105, 5, 'GADA ELECTRONICS');
INSERT INTO PRODUCT_DETAILS (ID, PROD_BRAND_MAP_ID , COLOR , PRICE , SIZE , SELLER ) VALUES (4,1, 'RED', 106, 6, 'GADA ELECTRONICS');
INSERT INTO PRODUCT_DETAILS (ID, PROD_BRAND_MAP_ID , COLOR , PRICE , SIZE , SELLER ) VALUES (5,3, 'BLUE', 110, 10, 'GADA ELECTRONICS');