DROP TABLE IF EXISTS PRODUCT;
CREATE TABLE PRODUCT (ID INT AUTO_INCREMENT PRIMARY KEY, NAME VARCHAR(255));
DROP TABLE IF EXISTS BRAND;
CREATE TABLE BRAND (ID INT AUTO_INCREMENT PRIMARY KEY, NAME VARCHAR(255));
DROP TABLE IF EXISTS PRODUCT_BRAND_MAPPING;
CREATE TABLE PRODUCT_BRAND_MAPPING (ID INT AUTO_INCREMENT PRIMARY KEY, BRAND_ID INT, PRODUCT_ID INT);
DROP TABLE IF EXISTS PRODUCT_DETAILS;
CREATE TABLE PRODUCT_DETAILS (ID INT AUTO_INCREMENT PRIMARY KEY, PROD_BRAND_MAP_ID INT(255), COLOR VARCHAR(255), PRICE INT, SIZE INT, SELLER VARCHAR(255));